# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 09:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('balance_update', models.FloatField()),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('isclosed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.DateField()),
                ('beleg', models.TextField()),
                ('op_beleg', models.TextField()),
                ('konto', models.TextField()),
                ('ust_code', models.PositiveSmallIntegerField()),
                ('uid_lieferant_kunde', models.TextField()),
                ('text', models.TextField()),
                ('kostenstelle', models.TextField()),
                ('steuersatz', models.PositiveSmallIntegerField()),
                ('eingang', models.FloatField()),
                ('ausgang', models.FloatField()),
                ('skonto', models.FloatField()),
                ('saldo', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('blance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Balance')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='balance',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
    ]
