# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160206_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='blance_id',
            new_name='blance',
        ),
    ]
