# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160213_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='blance',
            new_name='balance',
        ),
    ]
