# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160213_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='konto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='kostenstelle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='op_beleg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='uid_lieferant_kunde',
            field=models.TextField(blank=True, null=True),
        ),
    ]
