# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160214_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='validatedcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
